# Generated by Django 3.2.6 on 2022-10-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id_credito', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('valorCuota', models.IntegerField()),
                ('plazo', models.IntegerField()),
                ('tasa', models.IntegerField()),
                ('fechaPago', models.DateField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
