# Generated by Django 3.2.6 on 2022-10-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='id_cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
        ),
    ]
