# Generated by Django 3.2.6 on 2022-09-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaAfiliada',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('NIT', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('temporalidadContrato', models.IntegerField(blank=True, default=None, null=True)),
                ('formatoDocumento', models.CharField(max_length=50)),
            ],
        ),
    ]
