# Generated by Django 3.2.6 on 2022-10-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='documentoRevisar',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
