# Generated by Django 3.2.6 on 2022-10-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_solicitud_documentorevisar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='documentoRevisar',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='documentoCliente',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
