# Generated by Django 3.2.6 on 2022-09-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresaAfiliada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sueldo', models.FloatField(blank=True, default=None, null=True)),
                ('inicioContrato', models.DateField(blank=True, default=None, null=True)),
                ('descuentoRealizado', models.FloatField(blank=True, default=None, null=True)),
                ('numeroDocumento', models.FloatField(blank=True, default=None, null=True)),
                ('tipoDocumento', models.CharField(choices=[('cedula', 'CEDULA'), ('pasaporte', 'PASAPORTE')], default='cedula', max_length=50)),
                ('empresaAfiliada', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='empresaAfiliada.empresaafiliada')),
            ],
        ),
    ]
